export { default as IconArrowLeft } from './IconArrowLeft'
export { default as IconArrowRight } from './IconArrowRight'
export { default as IconBars } from './IconBars'
export { default as IconCross } from './IconCross'
export { default as IconFranceFlag } from './IconFranceFlag'
export { default as IconGlobeAmericas } from './IconGlobeAmericas'
export { default as IconLanguage } from './IconLanguage'
export { default as IconUkFlag } from './IconUkFlag'